package it.italiaonline.rnd

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 31-08-2017 14.22
 */
@Slf4j
class Library {
	/**
	 * This method returns always true.
	 */
	Boolean someLibraryMethod() {
		true
	}
}
