package it.italiaonline.rnd

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 31-08-2017 14.22
 */
class LibrarySpec extends Specification {
	def "someLibraryMethod returns true"() {
		setup:
			Library lib = new Library()
		when:
			Boolean result = lib.someLibraryMethod()
		then:
			result == true
	}
}
